### ISSUE TITLE
Websocket Connection Issue 

### ISSUE THREAD

**Issue by kalilinux-png** [AsthaTech/pyvortex#2]
Hi @brisingr123  

I was trying the WebSocket connection with python SDK and Node js 
when I tried to connect with Python SDK I faced this error 
![image](https://github.com/AsthaTech/pyvortex/assets/69741516/d16f2ae4-8cc4-4c7c-904f-73566dd7701a)
on the other side, I was not receiving correct data when I tried with node js SDK 
let me know if you need any details regarding this issue 

Thanks 
Shubham Yadav

**Comment by brisingr123** [comment]
what's the version of your python sdk ?

**Comment by brisingr123** [comment]
Please open a separate issue for node js sdk on ite repository. Request you to give sample of what you have received and what is expected.

**Comment by kalilinux-png** [comment]
👍
